/*
================================================================================
    02_Compliance_Reports.sql - تقارير الامتثال
    نظام التجارة الإلكترونية الآمن Oracle 19c
================================================================================
*/

ALTER SESSION SET CONTAINER = ECOM_PDB;

SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ========================================
PROMPT تقارير الامتثال
PROMPT ========================================

/*
================================================================================
    1. تقرير GDPR - البيانات الشخصية
================================================================================
*/

PROMPT [1] تقرير GDPR - البيانات الشخصية:

SELECT 
    'CUSTOMERS' AS TABLE_NAME,
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(EMAIL) AS EMAIL_COUNT,
    COUNT(PHONE) AS PHONE_COUNT,
    COUNT(NATIONAL_ID) AS NATIONAL_ID_COUNT,
    COUNT(DATE_OF_BIRTH) AS DOB_COUNT
FROM ECOM_OWNER.CUSTOMERS;

/*
================================================================================
    2. تقرير الوصول للبيانات الحساسة
================================================================================
*/

PROMPT [2] إحصائيات الوصول للبيانات الحساسة:

SELECT 
    DBUSERNAME,
    OBJECT_NAME,
    COUNT(*) AS ACCESS_COUNT,
    MIN(EVENT_TIMESTAMP) AS FIRST_ACCESS,
    MAX(EVENT_TIMESTAMP) AS LAST_ACCESS
FROM UNIFIED_AUDIT_TRAIL
WHERE OBJECT_SCHEMA = 'ECOM_OWNER'
AND OBJECT_NAME IN ('CUSTOMERS', 'PAYMENTS')
AND EVENT_TIMESTAMP > SYSDATE - 30
GROUP BY DBUSERNAME, OBJECT_NAME
ORDER BY ACCESS_COUNT DESC;

-- منح ECOM_OWNER صلاحيات مباشرة على جداول النظام لتمكين تجميع الإجراء
GRANT SELECT ON AUDIT_UNIFIED_ENABLED_POLICIES TO ECOM_OWNER;
GRANT SELECT ON DBA_POLICIES TO ECOM_OWNER;
GRANT SELECT ON REDACTION_POLICIES TO ECOM_OWNER;
GRANT SELECT ON DBA_AUDIT_POLICIES TO ECOM_OWNER;

/*
================================================================================
    3. تقرير سياسات الأمان المفعلة
================================================================================
*/

PROMPT [3] سياسات الأمان المفعلة:

-- VPD Policies
PROMPT VPD Policies:
SELECT OBJECT_NAME, POLICY_NAME, ENABLE
FROM DBA_POLICIES
WHERE OBJECT_OWNER = 'ECOM_OWNER';

-- Redaction Policies
PROMPT Data Redaction Policies:
SELECT OBJECT_NAME, POLICY_NAME, ENABLE
FROM REDACTION_POLICIES
WHERE OBJECT_OWNER = 'ECOM_OWNER';

-- Audit Policies
PROMPT Audit Policies:
SELECT POLICY_NAME, ENABLED_OPTION
FROM AUDIT_UNIFIED_ENABLED_POLICIES
WHERE POLICY_NAME LIKE 'ECOM_%';

/*
================================================================================
    4. تقرير المستخدمين والأدوار
================================================================================
*/

PROMPT [4] المستخدمون والأدوار:

SELECT 
    U.USERNAME,
    U.ACCOUNT_STATUS,
    U.PROFILE,
    LISTAGG(R.GRANTED_ROLE, ', ') WITHIN GROUP (ORDER BY R.GRANTED_ROLE) AS ROLES
FROM DBA_USERS U
LEFT JOIN DBA_ROLE_PRIVS R ON U.USERNAME = R.GRANTEE
WHERE U.USERNAME LIKE 'ECOM%' OR U.USERNAME IN ('SEC_ADMIN','CS_AGENT','WAREHOUSE_STAFF','SALES_REP','AUDITOR','REPORT_USER')
GROUP BY U.USERNAME, U.ACCOUNT_STATUS, U.PROFILE;

/*
================================================================================
    5. تقرير حماية البيانات
================================================================================
*/

PROMPT [5] ملخص حماية البيانات:

SELECT 
    (SELECT COUNT(*) FROM DBA_POLICIES WHERE OBJECT_OWNER = 'ECOM_OWNER') AS VPD_POLICIES,
    (SELECT COUNT(*) FROM REDACTION_POLICIES WHERE OBJECT_OWNER = 'ECOM_OWNER') AS REDACTION_POLICIES,
    (SELECT COUNT(*) FROM DBA_AUDIT_POLICIES WHERE OBJECT_SCHEMA = 'ECOM_OWNER') AS FGA_POLICIES,
    (SELECT COUNT(*) FROM AUDIT_UNIFIED_ENABLED_POLICIES WHERE POLICY_NAME LIKE 'ECOM_%') AS AUDIT_POLICIES
FROM DUAL;

/*
================================================================================
    6. توليد تقرير نصي
================================================================================
*/

-- ملاحظة: تم استخدام AUTHID CURRENT_USER لضمان عمل الإجراء بصلاحيات المنفذ
CREATE OR REPLACE PROCEDURE ECOM_OWNER.GENERATE_COMPLIANCE_REPORT 
AUTHID CURRENT_USER AS
BEGIN
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('COMPLIANCE REPORT - ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'));
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('Database: ' || SYS_CONTEXT('USERENV', 'DB_NAME'));
    DBMS_OUTPUT.PUT_LINE('PDB: ' || SYS_CONTEXT('USERENV', 'CON_NAME'));
    DBMS_OUTPUT.PUT_LINE('Generated by: ' || USER);
    DBMS_OUTPUT.PUT_LINE('========================================');
    
    FOR rec IN (
        SELECT POLICY_NAME FROM AUDIT_UNIFIED_ENABLED_POLICIES WHERE POLICY_NAME LIKE 'ECOM_%'
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Audit Policy: ' || rec.POLICY_NAME);
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('========================================');
    DBMS_OUTPUT.PUT_LINE('Report completed successfully');
END;
/

PROMPT تم إنشاء تقارير الامتثال ✓
