/*
================================================================================
    01_RBAC_Roles.sql - الأدوار والصلاحيات
    نظام التجارة الإلكترونية الآمن Oracle 19c
================================================================================
    المستخدم المطلوب: SYS AS SYSDBA
================================================================================
*/

ALTER SESSION SET CONTAINER = ECOM_PDB;

PROMPT ========================================
PROMPT إنشاء الأدوار والصلاحيات (RBAC)
PROMPT ========================================

/*
================================================================================
    1. الأدوار الأساسية
================================================================================
*/

-- دور المدير (جميع الصلاحيات)
CREATE ROLE ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.CUSTOMERS TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.PRODUCTS TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.ORDERS TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.ORDER_ITEMS TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.PAYMENTS TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.CATEGORIES TO ROLE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECOM_OWNER.ADDRESSES TO ROLE_ADMIN;
GRANT SELECT ON ECOM_OWNER.AUDIT_LOG TO ROLE_ADMIN;

-- دور مسؤول الأمان
CREATE ROLE ROLE_SECURITY;
GRANT SELECT ANY DICTIONARY TO ROLE_SECURITY;
GRANT EXECUTE ON DBMS_RLS TO ROLE_SECURITY;
GRANT EXECUTE ON DBMS_REDACT TO ROLE_SECURITY;
GRANT EXECUTE ON DBMS_FGA TO ROLE_SECURITY;
GRANT SELECT ON ECOM_OWNER.AUDIT_LOG TO ROLE_SECURITY;
GRANT SELECT ON ECOM_OWNER.SENSITIVE_DATA_ACCESS TO ROLE_SECURITY;
GRANT SELECT ON ECOM_OWNER.USER_SESSIONS TO ROLE_SECURITY;

-- دور المبيعات
CREATE ROLE ROLE_SALES;
GRANT SELECT ON ECOM_OWNER.PRODUCTS TO ROLE_SALES;
GRANT SELECT ON ECOM_OWNER.CATEGORIES TO ROLE_SALES;
GRANT SELECT, INSERT ON ECOM_OWNER.ORDERS TO ROLE_SALES;
GRANT SELECT, INSERT ON ECOM_OWNER.ORDER_ITEMS TO ROLE_SALES;
-- GRANT SELECT (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL) ON ECOM_OWNER.CUSTOMERS TO ROLE_SALES;
-- ملاحظة: Oracle لا تدعم منح صلاحية SELECT لأعمدة محددة مباشرة.
-- سيتم التعامل مع هذا باستخدام Views في الملف 04_Access_Views.sql

-- دور خدمة العملاء
CREATE ROLE ROLE_SUPPORT;
GRANT SELECT ON ECOM_OWNER.CUSTOMERS TO ROLE_SUPPORT;
GRANT SELECT, UPDATE (ORDER_STATUS, NOTES) ON ECOM_OWNER.ORDERS TO ROLE_SUPPORT;
GRANT SELECT ON ECOM_OWNER.ORDER_ITEMS TO ROLE_SUPPORT;
GRANT SELECT ON ECOM_OWNER.PRODUCTS TO ROLE_SUPPORT;
GRANT SELECT ON ECOM_OWNER.ADDRESSES TO ROLE_SUPPORT;

-- دور المستودع
CREATE ROLE ROLE_WAREHOUSE;
GRANT SELECT, UPDATE (STOCK_QUANTITY) ON ECOM_OWNER.PRODUCTS TO ROLE_WAREHOUSE;
GRANT SELECT, UPDATE (ORDER_STATUS, TRACKING_NUMBER, ACTUAL_DELIVERY) ON ECOM_OWNER.ORDERS TO ROLE_WAREHOUSE;
GRANT SELECT ON ECOM_OWNER.ORDER_ITEMS TO ROLE_WAREHOUSE;

-- دور المدقق
CREATE ROLE ROLE_AUDIT;
GRANT SELECT ON ECOM_OWNER.AUDIT_LOG TO ROLE_AUDIT;
GRANT SELECT ON ECOM_OWNER.SENSITIVE_DATA_ACCESS TO ROLE_AUDIT;
GRANT SELECT ON ECOM_OWNER.USER_SESSIONS TO ROLE_AUDIT;
GRANT AUDIT_VIEWER TO ROLE_AUDIT;

-- دور التقارير (قراءة فقط)
CREATE ROLE ROLE_READONLY;
GRANT SELECT ON ECOM_OWNER.CUSTOMERS TO ROLE_READONLY;
GRANT SELECT ON ECOM_OWNER.PRODUCTS TO ROLE_READONLY;
GRANT SELECT ON ECOM_OWNER.ORDERS TO ROLE_READONLY;
GRANT SELECT ON ECOM_OWNER.ORDER_ITEMS TO ROLE_READONLY;
GRANT SELECT ON ECOM_OWNER.CATEGORIES TO ROLE_READONLY;

/*
================================================================================
    2. تعيين الأدوار للمستخدمين
================================================================================
*/

GRANT ROLE_ADMIN TO ECOM_OWNER;
GRANT ROLE_ADMIN TO ECOM_MANAGER;
GRANT ROLE_SECURITY TO SEC_ADMIN;
GRANT ROLE_SALES TO SALES_REP;
GRANT ROLE_SUPPORT TO CS_AGENT;
GRANT ROLE_WAREHOUSE TO WAREHOUSE_STAFF;
GRANT ROLE_AUDIT TO AUDITOR;
GRANT ROLE_READONLY TO REPORT_USER;
GRANT ROLE_SALES, ROLE_SUPPORT TO APP_USER;

/*
================================================================================
    3. التحقق
================================================================================
*/

PROMPT الأدوار المنشأة:
SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'ROLE_%' ORDER BY ROLE;

PROMPT تم إنشاء الأدوار بنجاح ✓





SELECT ROLE FROM DBA_ROLES WHERE ROLE LIKE 'ROLE_%';

SELECT policy_name, enable FROM dba_policies WHERE object_owner = 'ECOM_OWNER';











