/*
================================================================================
    03_Load_Sample_Data.sql - تحميل بيانات الاختبار
    نظام التجارة الإلكترونية الآمن Oracle 19c
================================================================================
*/

SET DEFINE OFF;

PROMPT تحميل بيانات الاختبار...

-- الفئات
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, IS_ACTIVE, DISPLAY_ORDER) VALUES ('Electronics', 'إلكترونيات', 'الأجهزة الإلكترونية', 'Y', 1);
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, IS_ACTIVE, DISPLAY_ORDER) VALUES ('Clothing', 'ملابس', 'ملابس رجالية ونسائية', 'Y', 2);
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, IS_ACTIVE, DISPLAY_ORDER) VALUES ('Home & Garden', 'المنزل', 'مستلزمات المنزل', 'Y', 3);
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, IS_ACTIVE, DISPLAY_ORDER) VALUES ('Sports', 'رياضة', 'معدات رياضية', 'Y', 4);
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE) VALUES ('Mobile Phones', 'هواتف', 'الهواتف المحمولة', 1, 'Y');
INSERT INTO CATEGORIES (CATEGORY_NAME, CATEGORY_NAME_AR, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE) VALUES ('Laptops', 'لابتوب', 'الحواسيب', 1, 'Y');
COMMIT;
PROMPT ✓ الفئات (6)

-- المنتجات
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE, IS_FEATURED) VALUES ('ELEC-001', 'iPhone 15 Pro Max', 'آيفون 15 برو', 5, 5499.00, 4800.00, 50, 'Y', 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('ELEC-002', 'Samsung Galaxy S24', 'سامسونج S24', 5, 4999.00, 4200.00, 45, 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('ELEC-003', 'MacBook Pro 16', 'ماك بوك برو', 6, 12999.00, 11000.00, 20, 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('ELEC-004', 'Dell XPS 15', 'ديل XPS', 6, 8999.00, 7500.00, 30, 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('CLTH-001', 'Oxford Shirt', 'قميص أكسفورد', 2, 199.00, 80.00, 200, 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('HOME-001', 'Coffee Machine', 'ماكينة قهوة', 3, 599.00, 350.00, 80, 'Y');
INSERT INTO PRODUCTS (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_NAME_AR, CATEGORY_ID, UNIT_PRICE, COST_PRICE, STOCK_QUANTITY, IS_ACTIVE) VALUES ('SPRT-001', 'Running Shoes', 'حذاء جري', 4, 599.00, 300.00, 120, 'Y');
COMMIT;
PROMPT ✓ المنتجات (7)

-- العملاء
INSERT INTO CUSTOMERS (CUSTOMER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, GENDER, NATIONAL_ID, PASSWORD_HASH, IS_VERIFIED, CUSTOMER_TIER, ASSIGNED_AGENT) VALUES ('CUST-001', 'محمد', 'الأحمد', 'mohammed@email.com', '0501234567', DATE '1990-05-15', 'M', '1234567890', 'hash123', 'Y', 'GOLD', 'CS_AGENT');
INSERT INTO CUSTOMERS (CUSTOMER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, GENDER, NATIONAL_ID, PASSWORD_HASH, IS_VERIFIED, CUSTOMER_TIER) VALUES ('CUST-002', 'فاطمة', 'العلي', 'fatima@email.com', '0559876543', DATE '1985-08-20', 'F', '0987654321', 'hash456', 'Y', 'SILVER');
INSERT INTO CUSTOMERS (CUSTOMER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, GENDER, NATIONAL_ID, PASSWORD_HASH, IS_VERIFIED, CUSTOMER_TIER) VALUES ('CUST-003', 'عبدالله', 'السعيد', 'abdullah@email.com', '0551112222', DATE '1992-03-10', 'M', '1122334455', 'hash789', 'Y', 'PLATINUM');
INSERT INTO CUSTOMERS (CUSTOMER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, GENDER, NATIONAL_ID, PASSWORD_HASH) VALUES ('CUST-004', 'نورة', 'الخالد', 'noura@email.com', '0544445555', DATE '1988-11-25', 'F', '5544332211', 'hash101');
INSERT INTO CUSTOMERS (CUSTOMER_CODE, FIRST_NAME, LAST_NAME, EMAIL, PHONE, DATE_OF_BIRTH, GENDER, NATIONAL_ID, PASSWORD_HASH) VALUES ('CUST-005', 'أحمد', 'الفهد', 'ahmad@email.com', '0566667777', DATE '1995-07-08', 'M', '6677889900', 'hash102');
COMMIT;
PROMPT ✓ العملاء (5)

-- العناوين
INSERT INTO ADDRESSES (CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, CITY, STATE_PROVINCE, POSTAL_CODE, IS_DEFAULT, RECIPIENT_NAME) VALUES (1, 'BOTH', 'شارع الملك فهد، مبنى 25', 'الرياض', 'منطقة الرياض', '12345', 'Y', 'محمد الأحمد');
INSERT INTO ADDRESSES (CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, CITY, STATE_PROVINCE, POSTAL_CODE, IS_DEFAULT, RECIPIENT_NAME) VALUES (2, 'BOTH', 'حي النخيل، فيلا 42', 'جدة', 'منطقة مكة', '21432', 'Y', 'فاطمة العلي');
INSERT INTO ADDRESSES (CUSTOMER_ID, ADDRESS_TYPE, ADDRESS_LINE1, CITY, STATE_PROVINCE, POSTAL_CODE, IS_DEFAULT, RECIPIENT_NAME) VALUES (3, 'BOTH', 'شارع الأمير سلطان', 'الدمام', 'المنطقة الشرقية', '31452', 'Y', 'عبدالله السعيد');
COMMIT;
PROMPT ✓ العناوين (3)

-- Sequence للطلبات
CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- الطلبات
INSERT INTO ORDERS (ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_AMOUNT, TOTAL_AMOUNT, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, SHIPPING_METHOD) VALUES ('ORD-20240101-000001', 1, SYSTIMESTAMP-30, 'DELIVERED', 'PAID', 5499.00, 824.85, 0, 6323.85, 1, 1, 'EXPRESS');
INSERT INTO ORDERS (ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_AMOUNT, TOTAL_AMOUNT, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, SHIPPING_METHOD) VALUES ('ORD-20240102-000002', 2, SYSTIMESTAMP-15, 'SHIPPED', 'PAID', 1098.00, 164.70, 25.00, 1287.70, 2, 2, 'STANDARD');
INSERT INTO ORDERS (ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_AMOUNT, TOTAL_AMOUNT, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, SHIPPING_METHOD) VALUES ('ORD-20240103-000003', 3, SYSTIMESTAMP-5, 'CONFIRMED', 'PAID', 12999.00, 1949.85, 0, 14948.85, 3, 3, 'EXPRESS');
INSERT INTO ORDERS (ORDER_NUMBER, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_AMOUNT, TOTAL_AMOUNT, SHIPPING_ADDRESS_ID, BILLING_ADDRESS_ID, SHIPPING_METHOD) VALUES ('ORD-20240104-000004', 1, SYSTIMESTAMP-2, 'PENDING', 'PENDING', 599.00, 89.85, 25.00, 713.85, 1, 1, 'STANDARD');
COMMIT;
PROMPT ✓ الطلبات (4)

-- عناصر الطلبات
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT_PERCENT, LINE_TOTAL) VALUES (1, 1, 1, 5499.00, 0, 5499.00);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT_PERCENT, LINE_TOTAL) VALUES (2, 5, 2, 199.00, 0, 398.00);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT_PERCENT, LINE_TOTAL) VALUES (2, 6, 1, 599.00, 0, 599.00);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT_PERCENT, LINE_TOTAL) VALUES (3, 3, 1, 12999.00, 0, 12999.00);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, DISCOUNT_PERCENT, LINE_TOTAL) VALUES (4, 7, 1, 599.00, 0, 599.00);
COMMIT;
PROMPT ✓ عناصر الطلبات (5)

-- المدفوعات
INSERT INTO PAYMENTS (ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, AMOUNT, TRANSACTION_ID, CARD_LAST_FOUR, CARD_TOKEN, STATUS) VALUES (1, SYSTIMESTAMP-30, 'CREDIT_CARD', 6323.85, 'TXN-001', '4532', 'tok_visa_4532', 'COMPLETED');
INSERT INTO PAYMENTS (ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, AMOUNT, TRANSACTION_ID, CARD_LAST_FOUR, CARD_TOKEN, STATUS) VALUES (2, SYSTIMESTAMP-15, 'MADA', 1287.70, 'TXN-002', '8876', 'tok_mada_8876', 'COMPLETED');
INSERT INTO PAYMENTS (ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, AMOUNT, TRANSACTION_ID, STATUS) VALUES (3, SYSTIMESTAMP-5, 'APPLE_PAY', 14948.85, 'TXN-003', 'COMPLETED');
COMMIT;
PROMPT ✓ المدفوعات (3)

-- سجل التدقيق
INSERT INTO AUDIT_LOG (USERNAME, IP_ADDRESS, ACTION_TYPE, TABLE_NAME, DESCRIPTION, STATUS) VALUES ('ECOM_OWNER', '192.168.1.100', 'DATA_LOAD', 'ALL', 'تحميل البيانات الأولية', 'SUCCESS');
COMMIT;

PROMPT ========================================
PROMPT ملخص البيانات المحملة:
PROMPT ========================================
SELECT 'CATEGORIES' AS TBL, COUNT(*) AS CNT FROM CATEGORIES UNION ALL
SELECT 'PRODUCTS', COUNT(*) FROM PRODUCTS UNION ALL
SELECT 'CUSTOMERS', COUNT(*) FROM CUSTOMERS UNION ALL
SELECT 'ADDRESSES', COUNT(*) FROM ADDRESSES UNION ALL
SELECT 'ORDERS', COUNT(*) FROM ORDERS UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*) FROM ORDER_ITEMS UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM PAYMENTS;

PROMPT تم تحميل البيانات بنجاح ✓
