-- =========================================================
-- ملف: 05_Reset_Data.sql
-- الغرض: تنظيف الجداول وإعادة تعيين العدادات (Identity Columns)
-- المستخدم المطلوب: ECOM_OWNER
-- =========================================================

PROMPT جاري تنظيف الجداول وإعادة تعيين العدادات...

-- 1. تفريغ الجداول (مسح البيانات)
-- نستخدم CASCADE لحذف البيانات المرتبطة تلقائياً
TRUNCATE TABLE ORDER_ITEMS CASCADE;
TRUNCATE TABLE PAYMENTS CASCADE;
TRUNCATE TABLE USER_SESSIONS CASCADE;
TRUNCATE TABLE SENSITIVE_DATA_ACCESS CASCADE;
TRUNCATE TABLE AUDIT_LOG CASCADE;
-- الجداول الرئيسية
TRUNCATE TABLE ORDERS CASCADE;
TRUNCATE TABLE ADDRESSES CASCADE;
TRUNCATE TABLE PRODUCTS CASCADE;
TRUNCATE TABLE CATEGORIES CASCADE;
TRUNCATE TABLE CUSTOMERS CASCADE;

PROMPT ✓ تم تفريغ جميع الجداول

-- 2. إعادة تعيين العدادات (Identity Columns) لتبدأ من 1
ALTER TABLE CATEGORIES MODIFY (CATEGORY_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE PRODUCTS MODIFY (PRODUCT_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE CUSTOMERS MODIFY (CUSTOMER_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE ADDRESSES MODIFY (ADDRESS_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE ORDERS MODIFY (ORDER_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE ORDER_ITEMS MODIFY (ITEM_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE PAYMENTS MODIFY (PAYMENT_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE AUDIT_LOG MODIFY (LOG_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE USER_SESSIONS MODIFY (SESSION_ID GENERATED AS IDENTITY (START WITH 1));
ALTER TABLE SENSITIVE_DATA_ACCESS MODIFY (ACCESS_ID GENERATED AS IDENTITY (START WITH 1));

PROMPT ✓ تم إعادة تعيين العدادات (Identity Columns)

-- 3. إعادة تعيين Sequence الطلبات
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ORDERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL; -- تجاهل الخطأ إذا لم يكن موجوداً
END;
/
CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

PROMPT ✓ تم إعادة تعيين Sequence الطلبات

PROMPT ================================================
PROMPT النظام جاهز الآن لإعادة تحميل البيانات التجريبية
PROMPT ================================================
